### ISSUE TITLE
need to init flow with an own MockExternalContext

### ISSUE THREAD

**Issue by DerPyro** [lhug/spring-webflow-testing#1]
hey, it would be awesome if you could extend your _MockFlowTester_ method _startFlow_ to accept an **MockExternalContext** attribute. So you could evaluate expression like '_externalContext.nativeRequest.scheme'_ in the flow.

**Comment by lhug** [comment]
Passing ExternalContext is not a useful approach here.
However, as a first step, in version 1.3 it is possible to pass an object to be used as `nativeRequest` object.
More fields may be made available in time
